---
- name: Ensure apache is installed and started
  hosts: web
  become: yes
  user: root
  
  tasks:
  - name: Ensure latest index.html file is present
    copy:
      src: index.html
      dest: /var/www/html/

